import { Product } from '@/lib/types';

export const allProducts: Product[] = [
  // Pigs
  {
    id: 'pig-1',
    name: 'Hampshire Pig (Medium)',
    image: 'https://images.pexels.com/photos/6879777/pexels-photo-6879777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 45000,
    category: 'pigs',
    breed: 'Hampshire',
    size: 'Medium',
    inStock: true,
  },
  {
    id: 'pig-2',
    name: 'Yorkshire Pig (Large)',
    image: 'https://images.pexels.com/photos/110820/pexels-photo-110820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 65000,
    category: 'pigs',
    breed: 'Yorkshire',
    size: 'Large',
    inStock: true,
  },
  {
    id: 'pig-3',
    name: 'Duroc Pig (Small)',
    image: 'https://images.pexels.com/photos/162276/pig-domestic-pig-suckler-sow-162276.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 30000,
    category: 'pigs',
    breed: 'Duroc',
    size: 'Small',
    inStock: true,
  },
  {
    id: 'pig-4',
    name: 'Berkshire Pig (Medium)',
    image: 'https://images.pexels.com/photos/2218481/pexels-photo-2218481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 48000,
    category: 'pigs',
    breed: 'Berkshire',
    size: 'Medium',
    inStock: false,
  },

  // Pork
  {
    id: 'pork-1',
    name: 'Premium Pork Belly (1kg)',
    image: 'https://images.pexels.com/photos/6861257/pexels-photo-6861257.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 3500,
    category: 'pork',
    cut: 'Belly',
    weight: '1kg',
    inStock: true,
  },
  {
    id: 'pork-2',
    name: 'Pork Loin Chops (500g)',
    image: 'https://images.pexels.com/photos/5774154/pexels-photo-5774154.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 2800,
    category: 'pork',
    cut: 'Loin',
    weight: '500g',
    inStock: true,
  },
  {
    id: 'pork-3',
    name: 'Ground Pork (1kg)',
    image: 'https://images.pexels.com/photos/4969887/pexels-photo-4969887.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 3000,
    category: 'pork',
    cut: 'Ground',
    weight: '1kg',
    inStock: true,
  },
  {
    id: 'pork-4',
    name: 'Pork Ribs (1.5kg)',
    image: 'https://images.pexels.com/photos/7988252/pexels-photo-7988252.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 4200,
    category: 'pork',
    cut: 'Ribs',
    weight: '1.5kg',
    inStock: true,
  },

  // Foodstuff
  {
    id: 'food-1',
    name: 'Rice (5kg)',
    image: 'https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 5500,
    category: 'foodstuff',
    type: 'Grains',
    weight: '5kg',
    inStock: true,
  },
  {
    id: 'food-2',
    name: 'Palm Oil (2L)',
    image: 'https://images.pexels.com/photos/4033636/pexels-photo-4033636.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 3800,
    category: 'foodstuff',
    type: 'Oil',
    volume: '2L',
    inStock: true,
  },
  {
    id: 'food-3',
    name: 'Beans (2kg)',
    image: 'https://images.pexels.com/photos/6097872/pexels-photo-6097872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 2500,
    category: 'foodstuff',
    type: 'Legumes',
    weight: '2kg',
    inStock: true,
  },
  {
    id: 'food-4',
    name: 'Garri (5kg)',
    image: 'https://images.pexels.com/photos/6248853/pexels-photo-6248853.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 3200,
    category: 'foodstuff',
    type: 'Processed',
    weight: '5kg',
    inStock: true,
  },

  // Drinks
  {
    id: 'drink-1',
    name: 'Fruit Juice (1L)',
    image: 'https://images.pexels.com/photos/1337825/pexels-photo-1337825.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 1200,
    category: 'drinks',
    type: 'Juice',
    volume: '1L',
    inStock: true,
  },
  {
    id: 'drink-2',
    name: 'Soft Drink Pack (12 cans)',
    image: 'https://images.pexels.com/photos/2668308/pexels-photo-2668308.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 2800,
    category: 'drinks',
    type: 'Soda',
    quantity: '12 cans',
    inStock: true,
  },
  {
    id: 'drink-3',
    name: 'Water (12 bottles)',
    image: 'https://images.pexels.com/photos/327090/pexels-photo-327090.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 1500,
    category: 'drinks',
    type: 'Water',
    quantity: '12 bottles',
    inStock: true,
  },
  {
    id: 'drink-4',
    name: 'Wine Bottle (750ml)',
    image: 'https://images.pexels.com/photos/2912108/pexels-photo-2912108.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 4500,
    category: 'drinks',
    type: 'Alcohol',
    volume: '750ml',
    inStock: true,
  },
];